### ISSUE TITLE
No WebView plug-in found!

### ISSUE THREAD

**Issue by darkralts** [danieloneill/TwitchOverlay#13]
an error i got and havent managed to open the program
![image](https://user-images.githubusercontent.com/16366107/99612583-d99a1180-29e3-11eb-882e-e86dd2bb4f5a.png)
idk how to fix it

**Comment by danieloneill** [comment]
Currently the only way to authenticate with Twitch is via OAuth2 which uses a web-based authenticator.

I'm planning to play with new ways of authenticating to get rid of the WebView dependency, since it's about 95% of the release size and memory usage. Basically, it's Google Chrome and it's only used for Linking Account.

For now, though, you'll need those.

If you're using Qt 6.x the latest tag should work great. Also fixes a couple bugs from before that I didn't know about.

**Comment by darkralts** [comment]
🥖
