### ISSUE TITLE
Not Authenticating

### ISSUE THREAD

**Issue by klow9** [danieloneill/TwitchOverlay#9]
Twitch Key Authentication not working.

**Comment by danieloneill** [comment]
Hi @klow9, this is because my hosting provider for my server (which TwitchOverlay uses as a landing page for the oauth2 stuff) is having routing issues. It should resolve itself within 24 hours, hopefully...

Once it's up, I'll include the script used (just a single PHP script) so people can host their own OAuth2 landing page if they need, then just change the URL in the .qml file. Unfortunately, for now all we can do is wait until my hosting provider gets their act together.

Sorry m'homie, but it'll be back soon.  When it is, I'll close this report.
